name: HyperCrate
version: ${project.version}
main: run.tere.plugin.hypercrate.HyperCrate
api-version: 1.16
authors: [ tererun ]
description: HyperCrate is HyperCrate!
softdepend:
  - HolographicDisplays
commands:
  hypercrate:
    description: hypercrate commands!