name: HyperCrate
version: Patch-1.0.3
main: run.tere.plugin.hypercrate.HyperCrate
api-version: 1.16
authors: [ tererun ]
description: HyperCrate is HyperCrate!
softdepend:
  - HolographicDisplays
commands:
  hypercrate:
    description: hypercrate commands!